En utilisant numpy:

Ex 1 :Addition
Écrire un programme pour lire les éléments de deux matrices et ajoutez les deux matrices dans la troisième.

La somme de deux matrices de taille (m,n), $(A_{ij})$ et $(B_{ij})$ notée $A+B$  est à nouveau une matrice $(C_{ij})$ de taille (m,n), obtenue en additionnant les éléments correspondants: $(c_{ij}=a_{ij}+b_{ij})$


In [3]:
import numpy as np

def matrix_add(a, b,):
    return a+b

a = np.ones((4,4))
b = np.ones((4,4))

matrix_add(a,b)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

Ex2 :Multiplication
Écrire un programme pour lire les éléments de deux matrices, puis multipliez les deux matrices dans la troisième.

Deux matrices ne peuvent être multipliées que si le nombre de colonnes de la première matrice est le même que le nombre de lignes de la seconde matrice.

Si $ A=(a_{ij})$ est une matrice de taille (m,n), $ B=(b_{ij})$ et est une matrice de taille (n,p), alors leur produit, noté $AB=(c_{ij})$ est une matrice de taille (m,p) définie par :
$$\forall i,j : c_{ij}=\sum_{k=i}^{n} a_{ik}*b_{kj}$$

In [30]:
import numpy as np

def matrix_mul(a, b):
    if a.ndim == b.ndim == 2:
        if np.shape(a)[1] == np.shape(b)[0]:
            return np.matmul(a, b)
        else:
            print("Nombre de colonnes de A =", np.shape(a)[1], " != Nombres de lignes de B =", np.shape(b)[0])
    else:
        print("On ne peut multiplier que des matrices")
    

a = np.array([[1, 2], [3,4]])
b = np.array([[1], [2]])
matrix_mul(a,b) 

True


array([[ 5],
       [11]])

Ex 3: Matrice de Markov

Une matrice de Markov est une matrice carrée dont chaque élément est un réel compris entre 0 et 1 et dont la somme des éléments de chaque ligne vaut 1. Cela correspond, en probabilité, à la matrice de transition d'une chaîne de Markov finie.

Une matrice est dite bistochastique (ou doublement stochastique) si la somme des éléments de chaque ligne et de chaque colonne vaut 1.

1. Ecrire une fonction eststochastique(P) qui permet de vérifier est ce que la matrice P est stochastique ou non
2. Ecrire une fonction estbistochastique(P) qui permet de vérifier est ce que la matrice P est bistochastique ou non
3. Ecrire une fonction vecteurstable(G, h) qui permet de vérifier est ce que h est un vecteur stable de G ou non



In [52]:
import numpy as np

def est_stochastique(P):
    if P.ndim != 2:
        print("Pas une matrice")
        return
    for i in range(0, np.shape(P)[0]):
        sum = 0
        for j in range(0, np.shape(P)[1]):
            if not (0 <= P[i][j] <= 1) :
                print(f'P[{i}][{j}] = {P[i][j]} n\'est pas compris entre 0 et 1')
                return False
            sum += P[i][j]
        if sum != 1:
            print("La somme de la ligne", i, "=",sum,"ne fait pas 1")
            return False
    return True

def est_bistochastique(P):
    if P.ndim != 2:
        print("Pas une matrice")
        return
    for j in range(0, np.shape(P)[1]):
        sum = 0
        for i in range(0, np.shape(P)[0]):
            if not (0 <= P[i][j] <= 1) :
                print(f'P[{i}][{j}] = {P[i][j]} n\'est pas compris entre 0 et 1')
                return False
            sum += P[i][j]
        if sum != 1:
            print("La somme de la colonne", j, "=",sum,"ne fait pas 1")
            return False
    return True and est_stochastique(P)

a = np.array([[0,0.5,0.5], [0,1,0], [0.33, 0.34, 0.33]])
b = np.full((3,3), 1/3)
print(a)
print(b)
print(est_stochastique(a))
est_bistochastique(b)

[[0.   0.5  0.5 ]
 [0.   1.   0.  ]
 [0.33 0.34 0.33]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
True


True

Ex 4: Transposer

Programmer une fonction qui, étant donné une matrice à deux dimensions A, retourne la matrice B dont la première colonne est la première ligne de A, la seconde la deuxième ligne de A, etc. B s’appelle la transposée de A.

In [57]:
import numpy as np 

def transpose(a):
    if a.ndim !=2:
        print("Pas une matrice")
        return
    
    return np.transpose(a)

a = np.array([[1,2,3], [4,5,6]])

print(a)
print(transpose(a))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Ex 5: Permutations
1. $M$ désignant une matrice quelconque d’entiers à $l_i$ lignes et $co$ colonnes, $n$ un entier quelconque, programmer une fonction qui retourne la matrice $Sortie$ qui empile verticalement les $co+1$ matrices obtenues en adjoignant à $M$ une colonne $A$ à $li$ lignes dont tousles éléments sont égaux à $n$, $A$ étant placée d’abord devant $M$, puis entre la première et deuxième colonne de $M^a$,etc, jusqu’à ce que $A$ devienne sa dernière colonne. La matriceobtenue  aura $co+1$ colonnes et $(n+1)$ $li$ lignes

2. Écrire toutes les permutations de(1, ..., n)